"""foundation schema

Revision ID: 001
Revises: 
Create Date: 2026-06-24 15:29:14.111912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_users',
    sa.Column('customer_user_id', sa.Text(), nullable=False),
    sa.Column('firebase_uid', sa.Text(), nullable=True),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('phone_number', sa.Text(), nullable=False),
    sa.Column('birth_date', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('customer_user_id')
    )
    op.create_index(op.f('ix_customer_users_firebase_uid'), 'customer_users', ['firebase_uid'], unique=True)
    op.create_index(op.f('ix_customer_users_phone_number'), 'customer_users', ['phone_number'], unique=False)
    op.create_table('device_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fcm_token', sa.Text(), nullable=False),
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('user_type', sa.Text(), nullable=True),
    sa.Column('owner_ref', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fcm_token')
    )
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('table_prefix', sa.Text(), nullable=False),
    sa.Column('business_profile', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_prefix')
    )
    op.create_table('customer_tenant_memberships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_user_id', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('member_since', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['customer_user_id'], ['customer_users.customer_user_id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_user_id', 'tenant_id', name='uq_customer_tenant')
    )
    op.create_table('tenant_dpa_policies',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('allowed_rules', sa.JSON(), nullable=False),
    sa.Column('forbidden_rules', sa.JSON(), nullable=False),
    sa.Column('policy_summary', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('verified_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('tenant_settings',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('loyalty', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('tenant_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenant_users')
    op.drop_table('tenant_settings')
    op.drop_table('tenant_dpa_policies')
    op.drop_table('customer_tenant_memberships')
    op.drop_table('tenants')
    op.drop_table('device_tokens')
    op.drop_index(op.f('ix_customer_users_phone_number'), table_name='customer_users')
    op.drop_index(op.f('ix_customer_users_firebase_uid'), table_name='customer_users')
    op.drop_table('customer_users')
    # ### end Alembic commands ###
